language: node_js
node_js:
- '4.4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_URL=$(if test $TRAVIS_BRANCH = production; then echo "https://pwa.localnerve.net"; else echo "https://pwa-stage.localnerve.net"; fi)
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- echo DEPLOY_URL=$DEPLOY_URL
script:
- npm run test:cover
after_success:
- cat reports/coverage/lcov.info | ./node_modules/.bin/coveralls
before_deploy:
- npm run build:server
- rm -rf node_modules/
deploy:
  provider: heroku
  api_key:
    secure: oyi7w0/E7906PXl6BcRn8ufHys9phr1jperPFFDeSUUSJH/MkDK3CIKGGyfmP0vojUN5lwOwglJ/KcZarvMBrlPSdL/IcXAey9+y4digINyFQ/1fboS7+P4xV5MH2CP+sdqunEvEGV4g6Arcp3dZJs4tBar/KLwHr40YexWupqvxw4heDBI3xlx1uTK9mC5p2kokPxohZLSd2LXYJDJXYzwEvHdTp4b0E5yWeETXqPAt6OP/3Oc2Wb1+0U73FXmFN+hNdJMfazf0lTVwRLJ2Oxw18bcZhXCWM4CVrmYMyNFlgtshoVj+OHPzTcOIvTSAwFhkvyygMuyoIfcMIeVzW3Usato/v1htkn3GCooyyc+AV8H5aPP05PkJmTKmOvQesb/FhirXVzP2j7SeWVLq6A2zP4a9kQWyiUxySsIjX6OYcqFO4lZSxeQLCDM0VUZlR8fEQ2FZBTCXmQz39gCwlqD3cAq/lTI7L5d5aO6xXC/8faXXZw+Y5ZdR3HyPQokC0q+RO0pXyvYr05+ypMjZ3Ahvz99FFhYy9T9vaZ4RJEsZyT2P2qKhBKqvZm1J/XqUqa/G2FWLoiPhP9t5WJLeGQTRxildW0h+Ypa3cfUTepFF4BVgNd2zt5L2Q3znzkZkQS50QcKMHFtWK636Zdfy6zOD7t/yvOB1D+x/YCxb1dM=
  app:
    test: pwa-stage
    stage: pwa-stage
    master: pwa-stage
    production: pwa
  skip_cleanup: true
  run:
  - pushd output/node_modules
  - rm application
  - ln -s ../application application
  - popd
  - restart
  on:
    branch:
    - test
    - stage
    - master
    - production
    repo: localnerve/react-pwa-reference
    node: 4.4
